bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'€100,000',
  '200000':'€200,000',
  '300000':'€300,000',
  '400000':'€400,000',
  '500000':'€500,000',
  '600000':'€600,000',
  '700000':'€700,000',
  '800000':'€800,000',
  '900000':'€900,000',
  '1000000':'€1M+',
}

state_choices = {
        "Antrim" : "Co. Antrim",
        "Armagh" : "Co. Armagh",
        "Carlow" : "Co. Carlow",
        "Cavan" : "Co. Cavan",
        "Clare" : "Co. Clare",
        "Cork" : "Co. Cork",
        "Derry" : "Co. Derry ",
        "Donegal" : "Co. Donegal",
        "Down" : "Co. Down",
        "Dublin" : "Co. Dublin",
        "Fermanagh" : "Co. Fermanagh",
        "Galway" : "Co. Galway",
        "Kerry" : "Co. Kerry",
        "Kildare" : "Co. Kildare",
        "Kilkenny" : "Co. Kilkenny",
        "Laois" : "Co. Laois",
        "Leitrim" : "Co. Leitrim",
        "Limerick" : "Co. Limerick",
        "Longford" : "Co. Longford",
        "Louth" : "Co. Louth",
        "Mayo" : "Co. Mayo",
        "Meath" : "Co. Meath",
        "Monaghan" : "Co. Monaghan",
        "Offaly" : "Co. Offaly",
        "Roscommon" : "Co. Roscommon",
        "Sligo" : "Co. Sligo",
        "Tipperary" : "Co. Tipperary",
        "Tyrone" : "Co. Tyrone",
        "Waterford" : "Co. Waterford",
        "Westmeath" : "Co. Westmeath",
        "Wexford" :"Co. Wexford",
        "Wicklow" : "Co. Wicklow",
}